# Generated by Django 5.2.5 on 2025-09-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamil', models.IntegerField(default=0)),
                ('english', models.IntegerField(default=0)),
                ('maths', models.IntegerField(default=0)),
                ('science', models.IntegerField(default=0)),
                ('social_science', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('average', models.FloatField(default=0.0)),
                ('result', models.BooleanField(default=False)),
            ],
        ),
    ]
