# Generated by Django 5.2.5 on 2025-09-03 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_ranksheet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RankSheet',
        ),
        migrations.AddField(
            model_name='task',
            name='student_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.student'),
        ),
    ]
